const ANIMATION = {
  PACKET_SPEED: 0.04,
  DNS_SPEED: 0.06,
  DNS_FADE_DELAY: 200,
  PACKET_FINISH_DELAY: 500,
  HIGHLIGHT_TIMEOUT: 1500,
  DNS_NOTIFICATION_TIMEOUT: 2000,
  CLIPBOARD_FEEDBACK_TIMEOUT: 2000,
  MESSAGE_INDICATOR_TIMEOUT: 2000,
  SPECIAL_NODE_NOTIFICATION_TIMEOUT: 2000,
  NOTIFICATION_FADE_DELAY: 500,
};

const ZOOM = {
  MIN: 0.25,
  MAX: 4,
  WHEEL_FACTOR: 1.1,
};

const NODE = {
  MIN_RADIUS: 14,
  RADIUS_RATIO: 0.022,
  GRID_STEP_DIVISOR: 17,
};

const SUBNET = {
  MAX_CLIENTS: 3,
};

const ROOM = {
  CODE_MIN: 1000,
  CODE_MAX: 9000,
};

export { ANIMATION, ZOOM, NODE, SUBNET, ROOM };
